require:
  - rubocop-rails
  - rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.0
  TargetRailsVersion: 7.0.4
  NewCops: enable

Style/Documentation:
  Enabled: false
