require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.0
  TargetRailsVersion: 7.0.4
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*" # rubocop config/default.yml
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 20
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
