require:
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.0
  TargetRailsVersion: 7.0.4
  NewCops: enable
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
